### ISSUE TITLE
Project Crashes when doing testing

### ISSUE THREAD

**Issue by YYLee92** [ALIZE-Speaker-Recognition/android-alize-demo#1]
Hi All,

When I am doing speaker verification test  (from the "Test" button), sometimes the project will crash with the following error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.univavignon.alize.AndroidALIZEDemo, PID: 4603
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.io.FileNotFoundException: [ FileNotFoundException 0xcc9855d0 ]
      message   = ""
      source file = /home/duret/Dropbox/Alize/ferrone/android-alize/alize/src/main/cpp/alize-core/src/FileReader.cpp
      line number = 101
      fileName =  /data/user/0/fr.univavignon.alize.AndroidALIZEDemo/files/prm/181109_113743_7337431a.norm.prm
        at AlizeSpkRec.SimpleSpkDetSystem.createSpeakerModel(Native Method)
        at fr.univavignon.alize.AndroidALIZEDemo.EditSpeakerModelActivity$4.onClick(EditSpeakerModelActivity.java:134)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        	... 3 more
```

The error will not occur everytime, it will occur suddenly during one of our testing. When the error occur, all the speakers model that we have trained will be gone.

Another error that we faced is when we are saving the new speaker model after recording, the program will crash in the same way, but with a different error message as shown below:

			
```
E/AndroidRuntime: FATAL EXCEPTION: addSamples Thread
    Process: fr.univavignon.alize.AndroidALIZEDemo, PID: 4975
    java.io.IOException: [ IOException 0xe16625f0 ]
      message   = "Failed to parameterize audio file"
      source file = /home/duret/Dropbox/Alize/ferrone/android-alize/alize/src/main/cpp/LIA_RAL/LIA_SpkDet/SimpleSpkDetSystem/src/SimpleSpkDetSystem.cpp
      line number = 643
      fileName =  /data/user/0/fr.univavignon.alize.AndroidALIZEDemo/files/audio//181109_113931_474b456.audio
        at AlizeSpkRec.SimpleSpkDetSystem.addAudio(Native Method)
        at fr.univavignon.alize.AndroidALIZEDemo.RecordActivity$2.run(RecordActivity.java:237)
        at java.lang.Thread.run(Thread.java:764)
```

Kindly advice on what could be causing this issue and how we can resolve it?

Regards,
Yi Yang

**Comment by soundpoint** [comment]
Hi!
  Check .lbl/ directory. If its not empty - delete all .lbl files.

**Comment by YYLee92** [comment]
> Hi!
> Check .lbl/ directory. If its not empty - delete all .lbl files.

**Comment by YYLee92** [comment]
Hi soundpoint,

Do you mean the .lbl files under this directory /data/data/fr.univavignon.alize.AndroidALIZEDemo/files/lbl ?

**Comment by YYLee92** [comment]
Hi @soundpoint  ,

Thanks for the reply, but it does not solve the error.
Beside that error, I also found out the speaker model added is not saved and the next time I run the application, the previous trained speaker model is missing. 
How can we able to save the speaker model that we trained on this demo application and able to load it back when we run this application again?

Regards,
YiYang

**Comment by Ferrone84** [comment]
Hi, that should be fixed now. :smiley:
